# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2008-2017
  project: EXT: Project Tesseract
  version: 2.1
  release: 2.1.0
  latex_documents:
  - - Index
    - tesseract.tex
    - Data Filter
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    datafilter:
    - https://docs.typo3.org/typo3cms/extensions/datafilter/
    - null
    displaycontroller:
    - http://docs.typo3.org/typo3cms/extensions/displaycontroller/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...